name: "VEX V5 QEMU GitHub Action"
description: "Runs a VEX user program on a VEX V5 Brain simulator"
author: "Jerry Lum"
branding:
  icon: "package"
  color: "black"
inputs:
  target:
    description: "The target to run for"
    required: false
    default: "./bin/monolith.bin"
outputs:
  output:
    description: "The output of the program"
runs:
  using: "docker"
  image: "docker://ghcr.io/jerrylum/vex-v5-qemu-gh-action:main"
