[package]
name = "vex-v5-display-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
atools = "=0.1.4"
fimg = { version = "=0.4.41", features = ["save"] }
png = "0.17.13"
resource = "0.5.0"
rusttype = "0.9.3"

[lints]
workspace = true
