[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[dependencies]
host_call = { path = "../host_call" }
critical-section = { version = "1.1.2", features = ["restore-state-bool"] }
